path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari_17_23w/sub-FetalChiari_17_20161017080505_034_EPI_Survey_NEW_20timePts_JFE/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_17_34_20w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_17_34_20w'\
               --index_type=1\
               --resample=True\

path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari_17_23w/sub-FetalChiari_17_20161017080505_035_EPI_Survey_NEW_20timePts_JFE/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_17_35_20w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_17_35_20w'\
               --index_type=1\
               --resample=True\

path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari19_22w/sub-FetalChiari_19_20200824090112_011_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_19_11_22w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_19_11_22w'\
               --index_type=1\
               --resample=True\

path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari52_18w4d+21w1d/sub-FetalChiari52_18w4d+21w1d_20160921074225_022_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_52_22_18w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_52_22_18w'\
               --index_type=1\
               --resample=True\

path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari52_18w4d+21w1d/sub-FetalChiari52_18w4d+21w1d_20150921102908_041_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_52_41_18w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_52_41_18w'\
               --index_type=1\
               --resample=True\



path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari52_18w4d+21w1d/sub-FetalChiari52_18w4d+21w1d_20150921102908_042_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_52_42_18w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_52_42_18w'\
               --index_type=1\
               --resample=True\


path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari69_23w/sub-FetalChiari69_23w_20210510091925_038_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_69_38_23w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_69_38_23w'\
               --index_type=1\
               --resample=True\


path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari69_23w/sub-FetalChiari69_23w_20210510091925_041_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_69_41_23w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_69_41_23w'\
               --index_type=1\
               --resample=True\

path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari69_23w/sub-FetalChiari69_23w_20210510091925_044_EPI_Survey_NEW_20timePts_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_69_44_23w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_69_44_23w'\
               --index_type=1\
               --resample=True\

path='/unborn/shared/clinical-pose/clinical-pose/Chiari/FetalChiari70_18w2d/sub-FetalChiari70_18w2d_20140728095153_021_EPI_survey_20points_/'
chpk='/unborn/sdd/PyTorchPose/runs/augmentation-fixed/checkpoints/E399.pth'
bchpk='/unborn/sdd/PyTorchPose/runs/baseline-fixed/checkpoints/E300.pth'
python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$chpk\
               --output_path='./results/inference'\
               --label_name='C_70_21_18w'\
               --index_type=1\
               --resample=True\

python main.py --run_name=infer\
               --gpu_ids=0\
               --stage=inference\
               --rawdata_path=$path\
               --use_continue=True\
               --continue_path=$bchpk\
               --output_path='./results/inference'\
               --label_name='BC_70_21_18w'\
               --index_type=1\
               --resample=True\